version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - ollama

volumes:
  ollama-models:
